---
# Default values for icmp-responder.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

registry: docker.io
org: networkservicemesh
tag: master
pullPolicy: IfNotPresent

global:
  # set to true to enable Jaeger tracing for NSM components
  JaegerTracing: false
